export const topics = ['All posts', 'Recipes', 'Healthy eating', 'Kitchen tips', 'Kitchen stories'];
export const demoPosts = [
  { id: 'salad', name: 'Linh Nguyen', initials: 'LN', role: 'Home cook', time: '2 hours ago', topic: 'Healthy eating', title: 'A little salad for a lighter lunch', text: 'Pan-seared salmon, creamy avocado, and plenty of greens. A squeeze of lemon in the dressing makes this my favorite easy lunch. What do you add to yours?', image: 'https://www.themealdb.com/images/media/meals/1549542994.jpg', imageAlt: 'Salmon and avocado salad', likes: 128, comments: [{ name: 'Mai Anh', text: 'Those colors make me want to start cooking.' }, { name: 'Quang Minh', text: 'Trying the lemon dressing this weekend!' }], tags: ['eatclean', 'lunch', 'homecooking'] },
  { id: 'pho', name: 'Minh Anh', initials: 'MA', role: 'Recipe enthusiast', time: '4 hours ago', topic: 'Recipes', title: 'A weekend pot of pho for the whole family', text: 'Some meals taste even better when you make them together. We started the broth early, everyone helped, and the kitchen filled with wonderful aromas. Here is a little inspiration for your weekend.', image: 'https://www.themealdb.com/images/media/meals/pbzcrx1763765096.jpg', imageAlt: 'Beef pho with fresh herbs', likes: 96, comments: [{ name: 'Linh Nguyen', text: 'This is exactly what a weekend at home should look like.' }], tags: ['homecooking', 'vietnameserecipes'] },
  { id: 'tips', name: 'Hoang Nam', initials: 'HN', role: 'Curious cook', time: '5 hours ago', topic: 'Kitchen tips', title: 'Three small habits that make cooking easier', text: '1. Read the whole recipe before turning on the stove.\n2. Prepare and portion the ingredients first.\n3. Clean as you go while the food cooks.\n\nThese little habits make my kitchen feel less hectic. What works for you?', likes: 64, comments: [{ name: 'Thu Ha', text: 'Cleaning as I go has made such a difference.' }], tags: ['kitchentips', 'homecooking'] },
  { id: 'pasta', name: 'Thu Ha', initials: 'TH', role: 'Everyday cook', time: 'Yesterday', topic: 'Kitchen stories', title: 'A simple dinner after a long day', text: 'A bowl of Mediterranean pasta salad, a favorite song, and a little time to unwind. Sometimes a simple dinner is all you need. What did you cook today?', image: 'https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg', imageAlt: 'Mediterranean pasta salad', likes: 82, comments: [], tags: ['dinner', 'slowmoments'] },
];
export const groups = [
  { id: 'home', name: 'The home kitchen', members: '1,240', description: 'Recipes and stories from everyday home cooks.' },
  { id: 'green', name: 'Eat green, feel good', members: '856', description: 'Fresh ideas for adding more greens to your plate.' },
  { id: 'new', name: 'First-time cooks', members: '632', description: 'A place to learn, ask questions, and try something new.' },
];
