import { useState } from "react";
import { Link } from "react-router-dom";
import { useAssistant } from "./AssistantContext";
import { Shell, Status } from "./shared";
function Content() {
  const { today, api, refresh } = useAssistant();
  const [name, setName] = useState(""), [childName, setChildName] = useState(""), [birthDate, setBirthDate] = useState(""), [link, setLink] = useState(""), [token, setToken] = useState(new URLSearchParams(window.location.hash.slice(1)).get("invite") || ""), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const run = async action => { setBusy(true); setError(""); setMessage(""); try { await action(); await refresh(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <><Status error={error} message={message} /><div className="ai-grid"><div className="ai-card"><h2>{today.household?.name || "Your family, together"}</h2>{!today.household ? <form onSubmit={e => { e.preventDefault(); run(() => api("/households", { name })); }}><label>Family name<input required value={name} onChange={e => setName(e.target.value)} placeholder="The Nguyen family" /></label><div className="ai-actions"><button className="primary" disabled={busy}>Create family</button></div></form> : <><p>Shared meals. Personal preferences. You choose which indicators others can see.</p><ul className="ai-list">{today.members.map(m => <li key={m.id}><div><strong>{m.name}</strong><p className="ai-muted">{m.child ? "Child · guardian managed" : "Adult · own profile"} · {m.sharing.portions ? "Meal preferences shared" : "Meal preferences private"}</p></div><Link to="/profile">Profile</Link></li>)}</ul>{today.household.isOwner && <div className="ai-actions"><button disabled={busy} onClick={() => run(async () => { const result = await api("/invites", {}); setLink(window.location.origin + "/family#invite=" + result.token); })}>Create adult invitation</button></div>}{link && <label className="wide">Invitation · expires in 24 hours<input readOnly value={link} /><button onClick={async () => { try { await navigator.clipboard.writeText(link); setMessage("Invitation copied. Share it with the adult you want to invite."); } catch { setMessage("Select and copy the invitation link above."); } }}>Copy link</button></label>}
      {today.household.isOwner && today.members.filter(m => !m.child && m.id !== today.profile.id).length > 0 && <label>Transfer ownership<select defaultValue="" onChange={e => { if (e.target.value) run(() => api("/households/transfer", { memberId: e.target.value })); }}><option value="">Choose an adult</option>{today.members.filter(m => !m.child && m.id !== today.profile.id).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label>}
      <div className="ai-actions"><button className="danger" disabled={busy} onClick={() => run(() => api("/households/leave", {}))}>Leave family</button></div></>}</div>
    {today.household && <form className="ai-card" onSubmit={e => { e.preventDefault(); run(async () => { await api("/members", { name: childName, birthDate }); setChildName(""); setBirthDate(""); setMessage("Child profile created. Add dietary preferences in Profile."); }); }}><h2>Add a child</h2><p>You manage this child's profile and meal diary. Available for ages 2–17.</p><div className="ai-fields"><label>Name<input required value={childName} onChange={e => setChildName(e.target.value)} /></label><label>Date of birth<input type="date" required value={birthDate} onChange={e => setBirthDate(e.target.value)} /></label></div><div className="ai-actions"><button className="primary" disabled={busy}>Add child profile</button></div></form>}
    {!today.household && <form className="ai-card" onSubmit={e => { e.preventDefault(); run(async () => { await api("/invites/accept", { token }); window.history.replaceState(null, "", "/family"); setToken(""); setMessage("You joined the family."); }); }}><h2>Accept an invitation</h2><p>Complete your adult Profile first. Joining shares dietary preferences; your body history stays private.</p><label>Invitation token<input required value={token} onChange={e => setToken(e.target.value.includes("invite=") ? e.target.value.split("invite=")[1] : e.target.value)} /></label><div className="ai-actions"><button className="primary" disabled={busy || today.demo}>Accept & join family</button></div></form>}
  </div></>;
}
export default function Family() { return <Shell title="Family" description="One table, with room for everyone's needs."><Content /></Shell>; }
