import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAssistant } from "./AssistantContext";
import { Shell, PlanCard, Status } from "./shared";
const slots = ["breakfast", "lunch", "dinner"];
function Editor({ date, catalog, onPreview, busy }) {
  const { today } = useAssistant();
  const members = today.members.filter(m => m.editable || m.sharing.portions);
  const portions = () => Object.fromEntries(members.map(m => [m.id, m.portion || 1]));
  const [slot, setSlot] = useState("dinner"), [dishes, setDishes] = useState([{ mealId: "", portions: portions() }]);
  const update = (index, patch) => setDishes(rows => rows.map((d, i) => i === index ? { ...d, ...patch } : d));
  return <form className="ai-card" onSubmit={e => { e.preventDefault(); onPreview({ date, slots: [slot], selections: { [slot]: dishes } }); }}><h2>Build a shared meal</h2><p>Choose dishes for a Vietnamese meal or an international plate, then confirm who is eating and their recipe servings.</p><label>Meal slot<select value={slot} onChange={e => setSlot(e.target.value)}>{slots.map(x => <option key={x}>{x}</option>)}</select></label>{dishes.map((dish, index) => <div className="ai-card soft" key={index} style={{ marginTop: 14 }}><label>Dish {index + 1}<select required value={dish.mealId} onChange={e => update(index, { mealId: e.target.value })}><option value="">Choose a recipe</option>{catalog.map(m => <option value={m.id} key={m.id}>{m.name}</option>)}</select></label><div className="ai-fields" style={{ marginTop: 12 }}>{members.map(m => <div key={m.id}><label className="ai-check"><input type="checkbox" checked={Boolean(dish.portions[m.id])} onChange={e => { const next = { ...dish.portions }; if (e.target.checked) next[m.id] = m.portion || 1; else delete next[m.id]; update(index, { portions: next }); }} />{m.name}</label>{dish.portions[m.id] && <label>Recipe servings<input type="number" min="0.1" max="10" step="0.1" value={dish.portions[m.id]} onChange={e => update(index, { portions: { ...dish.portions, [m.id]: Number(e.target.value) } })} /></label>}</div>)}</div>{dishes.length > 1 && <button type="button" onClick={() => setDishes(rows => rows.filter((_, i) => i !== index))}>Remove dish</button>}</div>)}<div className="ai-actions"><button type="button" disabled={dishes.length >= 8} onClick={() => setDishes(rows => [...rows, { mealId: "", portions: portions() }])}>Add another dish</button><button className="primary" disabled={busy}>Preview meal</button></div></form>;
}
function Content() {
  const { today, api, refresh } = useAssistant();
  const [date, setDate] = useState(today.date), [start, setStart] = useState(today.week), [plans, setPlans] = useState([]), [catalog, setCatalog] = useState([]), [preview, setPreview] = useState(null), [weekly, setWeekly] = useState(null), [cart, setCart] = useState(null), [pantry, setPantry] = useState([]), [ingredient, setIngredient] = useState(""), [summary, setSummary] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const fetchAll = () => Promise.all([api("/plans?start=" + start), api("/catalog"), api("/groceries?start=" + start), api("/pantry"), api("/summary?start=" + start)]);
  const apply = ([p, c, g, stock, recap]) => { setPlans(p); setCatalog(c.meals); setCart(g); setPantry(stock); setSummary(recap); };
  const load = async () => apply(await fetchAll());
  useEffect(() => { let active = true; Promise.all([api("/plans?start=" + start), api("/catalog"), api("/groceries?start=" + start), api("/pantry"), api("/summary?start=" + start)]).then(data => { if (active) { const [p, c, g, stock, recap] = data; setPlans(p); setCatalog(c.meals); setCart(g); setPantry(stock); setSummary(recap); } }).catch(e => { if (active) { setError(e.message); setCart(null); setPlans([]); } }); return () => { active = false; }; }, [api, start]);
  const run = async action => { setBusy(true); setError(""); setMessage(""); try { await action(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const confirm = id => run(async () => { await api(`/plan-proposals/${id}/confirm`, {}); setPreview(null); setWeekly(null); await load(); await refresh(); setMessage("Plan saved. Groceries reflect the confirmed portions."); });
  const download = () => { const body = ["EatVibing family groceries", "Week: " + start, ...(cart?.items || []).map(i => i.label), ...(cart?.warnings || [])].join("\n"); const url = URL.createObjectURL(new Blob([body], { type: "text/plain;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "eatvibing-family-groceries.txt"; a.click(); URL.revokeObjectURL(url); };
  return <><Status error={error} message={message} /><div className="ai-card soft"><div className="ai-fields"><label>Week starts Monday<input type="date" value={start} onChange={e => { setStart(e.target.value); setWeekly(null); setPreview(null); }} /></label><label>Day to plan<input type="date" value={date} onChange={e => { setDate(e.target.value); setPreview(null); }} /></label></div><div className="ai-actions"><button className="primary" disabled={busy} onClick={() => run(async () => { setWeekly(await api("/weekly-proposals", { start })); setPreview(null); })}>Preview full week</button><button disabled={busy} onClick={() => run(async () => { setWeekly(await api("/weekly-proposals", { start, reusePrevious: true })); setPreview(null); })}>Reuse previous week</button><button disabled={busy} onClick={() => run(async () => { setPreview(await api("/plan-proposals", { date })); setWeekly(null); })}>Suggest selected day</button><Link className="ai-button" to="/planner">Original recipe planner</Link></div><p className="ai-muted">Suggestions follow known preferences. Exact calorie matching awaits reviewed nutrition and policy.</p></div>
    {weekly && <><div className="ai-card"><h2>Your week · Preview</h2><p>All days are saved together; failed validation keeps the existing week.</p><button className="primary" disabled={busy} onClick={() => confirm(weekly.id)}>Confirm full week</button></div><div className="ai-day-grid">{weekly.days.map(p => <PlanCard key={p.id} plan={p} members={today.members} />)}</div></>}
    {preview && <PlanCard plan={preview} members={today.members} busy={busy} onConfirm={confirm} />}
    <details className="ai-card"><summary>Import a demo plan</summary><p>Choose a plan JSON file to preview. Imported servings belong to your profile; review family portions in the meal editor. Your current plans change only after confirmation.</p><label>Plan file<input type="file" accept="application/json,.json" disabled={busy} onChange={e => { const file = e.target.files?.[0]; if (!file) return; run(async () => { if (file.size > 100000) throw new Error("Choose a plan file under 100 KB."); const data = JSON.parse(await file.text()); setWeekly(await api("/demo-imports", { days: data.days })); setPreview(null); }); e.target.value = ""; }} /></label><p className="ai-muted">Format: days with a date, entries with a meal slot, and dishes with recipe ID and servings. See the assistant setup guide for an example. Account, household and visitor IDs are never imported.</p></details>
    <Editor key={date + today.members.map(m => m.id).join()} date={date} catalog={catalog} busy={busy} onPreview={body => run(async () => { setPreview(await api("/plan-proposals", body)); setWeekly(null); })} />
    <h2>Confirmed meals</h2>{!plans.length && <div className="ai-card ai-empty"><p>Your confirmed plans will appear here.</p></div>}<div className="ai-day-grid">{plans.map(p => <PlanCard key={p.date} plan={p} members={today.members} busy={busy} onLock={(slot, locked) => run(async () => { await api("/plans/lock", { date: p.date, slot, locked }); await load(); })} onSwap={slot => run(async () => { setPreview(await api("/plan-proposals", { date: p.date, slots: [slot], swap: true })); setWeekly(null); })} />)}</div>
    <div className="ai-grid"><div className="ai-card" id="groceries"><h2>Family groceries</h2><p>Current week's ingredients, adjusted for participants and pantry.</p>{cart?.items.length ? <><ul className="ai-list">{cart.items.map(i => <li key={i.key}><label className="ai-check"><input type="checkbox" disabled={busy || i.covered} checked={i.checked || i.covered} onChange={e => run(async () => { await api("/groceries/check", { start, signature: cart.signature, key: i.key, checked: e.target.checked }); setCart(await api("/groceries?start=" + start)); })} /><span>{i.label}{i.covered && <span className="ai-pill">In pantry</span>}</span></label></li>)}</ul><div className="ai-actions"><button onClick={download}>Download list</button><button disabled={busy} onClick={() => run(load)}>Refresh</button></div></> : <p>Confirm meals to build your list.</p>}{cart?.warnings.length > 0 && <details><summary>Quantity checks ({cart.warnings.length})</summary>{cart.warnings.map(w => <p className="ai-muted" key={w}>{w}</p>)}</details>}</div><div className="ai-card"><h2>Family pantry</h2><form onSubmit={e => { e.preventDefault(); run(async () => { await api("/pantry", { text: ingredient }); setIngredient(""); await load(); }); }}><label>Ingredient & quantity<input required value={ingredient} onChange={e => setIngredient(e.target.value)} placeholder="200 g chicken breast" /></label><div className="ai-actions"><button disabled={busy}>Add ingredient</button></div></form><ul className="ai-list">{pantry.map(p => <li key={p.id}><span>{p.raw}</span><button disabled={busy} onClick={() => run(async () => { await api("/pantry", { remove: p.id }); await load(); })}>Remove</button></li>)}</ul></div></div>
    {summary && <div className="ai-card"><h2>Weekly recap</h2><p>{summary.recordedMeals} meals recorded · {summary.unknownMeals} unknown meals · {summary.checkIns} check-ins.</p><p className="ai-muted">Your goal stays as you set it. Tell us what worked and what made meals difficult.</p><form className="ai-fields" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); run(async () => { await api("/feedback", { mealId: f.get("mealId"), rating: f.get("rating"), reason: f.get("reason") }); setMessage("Feedback saved for future suggestions."); }); }}><label>Recipe<select required name="mealId"><option value="">Choose a recipe</option>{catalog.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Feedback<select name="rating"><option value="like">I'd like this again</option><option value="dislike">I'd prefer something else</option></select></label><label>Reason<select name="reason">{["taste", "ingredients", "time", "repeat", "other"].map(x => <option key={x}>{x}</option>)}</select></label><div className="ai-actions"><button disabled={busy}>Save feedback</button></div></form></div>}
  </>;
}
export default function Planner() { return <Shell title="Your family planner" description="Shared dishes, individual portions and one grocery list."><Content /></Shell>; }
