import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAssistant } from "./AssistantContext";
import { Shell, Status, MemberSelect, Metrics, PlanCard } from "./shared";
const slots = ["breakfast", "lunch", "dinner"];
function CheckIn({ memberId }) {
  const { today, api, refresh } = useAssistant();
  const p = today.members.find(m => m.id === memberId);
  const [form, setForm] = useState({ date: today.date, dayActivity: p.activity || "sedentary", activity: p.usualActivity || "", activityMinutes: p.usualActivityMinutes || 0, activityStatus: "planned", cookingMinutes: p.cookingMinutes || 30, locations: { breakfast: "home", lunch: p.child ? "unknown" : "home", dinner: "home" } });
  const [error, setError] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; api(`/check-ins?memberId=${encodeURIComponent(memberId)}&date=${today.date}`).then(data => { if (active && data) setForm(data); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [api, memberId, today.date]);
  const change = (key, value) => setForm(f => ({ ...f, [key]: value }));
  return <form className="ai-card" id="check-in" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); try { await api("/check-ins", { ...form, memberId }); await refresh(); setMessage("Check-in saved. Planned activity stays separate from completed activity."); } catch (e) { setError(e.message); } finally { setBusy(false); } }}><h2>A quick check-in</h2><p>What does {p.child ? p.name + "'s" : "your"} day look like?</p><div className="ai-fields"><label>Whole-day activity<select value={form.dayActivity} onChange={e => change("dayActivity", e.target.value)}>{["sedentary", "light", "moderate", "active"].map(x => <option key={x} value={x}>{x}</option>)}</select></label><label>Cooking time (minutes)<input type="number" min="5" max="240" value={form.cookingMinutes} onChange={e => change("cookingMinutes", Number(e.target.value))} /></label><label>Activity / workout<input value={form.activity} onChange={e => change("activity", e.target.value)} placeholder="Walking, swimming, gym…" /></label><label>Activity minutes<input type="number" min="0" max="600" value={form.activityMinutes} onChange={e => change("activityMinutes", Number(e.target.value))} /></label><label>Status<select value={form.activityStatus} onChange={e => change("activityStatus", e.target.value)}><option value="planned">Planned</option><option value="completed">Completed</option><option value="none">No additional activity</option></select></label>{slots.map(slot => <label key={slot}>{slot} location<select value={form.locations[slot]} onChange={e => change("locations", { ...form.locations, [slot]: e.target.value })}><option value="home">At home · join family meal</option><option value="outside">Outside / school / work</option><option value="unknown">Not sure yet</option></select></label>)}</div><Status error={error} message={message} /><div className="ai-actions"><button className="primary" disabled={busy}>Save today's check-in</button><button type="button" onClick={() => setForm(f => ({ ...f, dayActivity: p.activity || "sedentary", activity: p.usualActivity || "", activityMinutes: p.usualActivityMinutes || 0, activityStatus: "planned", cookingMinutes: p.cookingMinutes || 30 }))}>Use usual schedule</button></div></form>;
}
function MealLog({ memberId }) {
  const { today, api, refresh } = useAssistant();
  const [catalog, setCatalog] = useState([]), [logs, setLogs] = useState([]), [slot, setSlot] = useState("breakfast"), [status, setStatus] = useState("recorded"), [meal, setMeal] = useState(""), [servings, setServings] = useState(1), [note, setNote] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  useEffect(() => { let active = true; Promise.all([api("/catalog"), api(`/meal-logs?memberId=${encodeURIComponent(memberId)}&date=${today.date}`)]).then(([data, rows]) => { if (active) { setCatalog(data.meals); setLogs(rows); } }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [api, memberId, today.date]);
  return <form className="ai-card" id="meal-log" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); try { await api("/meal-logs", { memberId, date: today.date, slot, status, dishes: meal ? [{ mealId: meal, servings }] : [], note }); setLogs(await api(`/meal-logs?memberId=${encodeURIComponent(memberId)}&date=${today.date}`)); await refresh(); setMessage("Meal diary updated."); } catch (e) { setError(e.message); } finally { setBusy(false); } }}><h2>Record a meal</h2><p>Record what was eaten. Unknown meals remain unknown.</p><div className="ai-fields"><label>Meal<select value={slot} onChange={e => setSlot(e.target.value)}>{slots.map(s => <option key={s}>{s}</option>)}</select></label><label>Diary status<select value={status} onChange={e => setStatus(e.target.value)}><option value="recorded">Eaten / recorded</option><option value="unknown">Unknown · e.g. school meal</option><option value="skipped">Skipped / not eaten</option></select></label>{status === "recorded" && <><label className="wide">Recipe (optional for eating out)<select value={meal} onChange={e => setMeal(e.target.value)}><option value="">Describe outside meal in notes</option>{catalog.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Actual recipe servings<input type="number" min="0.1" max="10" step="0.1" value={servings} onChange={e => setServings(Number(e.target.value))} /></label></>}<label className="wide">Notes<textarea value={note} maxLength={500} onChange={e => setNote(e.target.value)} placeholder="What was eaten or what is still unknown" /></label></div><Status error={error} message={message} /><div className="ai-actions"><button className="primary" disabled={busy}>Save meal record</button></div><ul className="ai-list">{logs.map(l => <li key={l.id}><span>{l.slot}</span><span className="ai-pill">{l.status}</span></li>)}</ul></form>;
}
function Content() {
  const { today, api, refresh } = useAssistant();
  const [memberId, setMemberId] = useState(today.profile.id), [preview, setPreview] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const run = async action => { setBusy(true); setError(""); try { await action(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <><div className="ai-grid"><div className="ai-card soft full"><div className="ai-eyebrow">Your daily picture</div><h2>Hello, {today.profile.name}</h2><Metrics value={today.metrics} /><div className="ai-actions">{today.actions.map(a => <Link className="ai-button" key={a.to} to={a.to}>{a.label}</Link>)}</div></div><div className="ai-card"><h2>Food recorded today</h2><p>{today.intake.complete ? "Your three main meals have reviewed nutrition." : "Your diary is incomplete or nutrition data is missing."}</p><strong>{today.intake.values ? today.intake.values.kcal + " kcal recorded" : "Total unavailable"}</strong><p className="ai-muted">{today.intake.note}</p></div><div className="ai-card"><h2>{new Date(today.date + "T12:00:00Z").getUTCDay() === 1 ? "Start your week" : "Meals that fit today"}</h2><p>Preview a shared meal plan and confirm each person's recipe servings.</p><div className="ai-actions"><button className="primary" disabled={busy} onClick={() => run(async () => setPreview(await api("/plan-proposals", { date: today.date })))}>Preview today's meals</button><Link className="ai-button" to="/family-planner">Plan the week</Link></div></div></div><Status error={error} />{preview && <PlanCard plan={preview} members={today.members} busy={busy} onConfirm={id => run(async () => { await api(`/plan-proposals/${id}/confirm`, {}); setPreview(null); await refresh(); })} />}{today.plan && <PlanCard plan={today.plan} members={today.members} />}
  <div className="ai-card"><MemberSelect editableOnly value={memberId} onChange={setMemberId} /></div><div className="ai-grid"><CheckIn key={"check-" + memberId} memberId={memberId} /><MealLog key={"log-" + memberId} memberId={memberId} /></div></>;
}
export default function Today() { return <Shell title="Today, made personal" description="A short check-in. Meals for your day. A shared table for your family."><Content /></Shell>; }
